services:
  - type: web
    name: petstore-backend
    env: docker
    branch: master
    rootDir: backend
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: '8080'

  - type: static
    name: petstore-frontend
    env: static
    branch: master
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishPath: dist
    plan: free
